version: '3.8'

services:
  horizon-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yinni-web
    ports:
      - "3000:80" # Maps your computer's port 3000 to the container's port 80
    restart: always